### ISSUE TITLE
mysqld: Table 'mysql.plugin' doesn't exist

### ISSUE THREAD

**Issue by Nihal987** [wagnerjfr/mysql-group-replication-docker#6]
I get ran the docker command exactly as mentioned in the medium article, but I get this error from my docker container and the container eventually goes down.
I've tried running a single container with this set of instructions.

```
docker run -d --name=node1  \
-e MYSQL_ROOT_PASSWORD=mypass \
-v data:/var/lib/mysql \
mysql/mysql-server:8.0 \
--server-id=1 \
--log-bin='mysql-bin-1.log' \
--enforce-gtid-consistency='ON' \
--log-slave-updates='ON' \
--gtid-mode='ON' \
--transaction-write-set-extraction='XXHASH64' \
--binlog-checksum='NONE' \
--master-info-repository='TABLE' \
--relay-log-info-repository='TABLE' \
--plugin-load='group_replication.so' \
--relay-log-recovery='ON' \
--group-replication-group-name='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' \
--group-replication-local-address="node$N:33061" \
--group-replication-group-seeds='node1:33061,node2:33061,node3:33061' \
--loose-group-replication-single-primary-mode='OFF' \
--loose-group-replication-enforce-update-everywhere-checks='ON'
```

And these are the logs that are generated.
```
[Entrypoint] MySQL Docker Image 8.0.32-1.2.11-server
[Entrypoint] Starting MySQL 8.0.32-1.2.11-server
[Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
[Warning] [MY-011068] [Server] The syntax 'log_slave_updates' is deprecated and will be removed in a future release. Please use log_replica_updates instead.
[Warning] [MY-011069] [Server] The syntax '--transaction-write-set-extraction' is deprecated and will be removed in a future release.
[Warning] [MY-011069] [Server] The syntax '--master-info-repository' is deprecated and will be removed in a future release.
[Warning] [MY-011069] [Server] The syntax '--relay-log-info-repository' is deprecated and will be removed in a future release.
[System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
[System] [MY-013576] [InnoDB] InnoDB initialization has started.
[System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysqld: Table 'mysql.plugin' doesn't exist
[ERROR] [MY-010735] [Server] Could not open the mysql.plugin table. Please perform the MySQL upgrade procedure.
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[System] [MY-013587] [Repl] Plugin group_replication reported: 'Plugin 'group_replication' is starting.'
[Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
[Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
[Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
[System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
[Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
[ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
[Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
[ERROR] [MY-010326] [Server] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2023-08-09T14:24:45.427216Z 0 [ERROR] [MY-010952] [Server] The privilege system failed to initialize correctly. For complete instructions on how to upgrade MySQL to a new version please see the 'Upgrading MySQL' section from the MySQL manual.
[ERROR] [MY-010119] [Server] Aborting
[ERROR] [MY-011563] [Repl] Plugin group_replication reported: 'Unable to start Group Replication. Replication applier infrastructure is not initialized since the server was started with --initialize, --initialize-insecure or --upgrade=MINIMAL on a server upgrade.'
[System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
```

**Comment by wagnerjfr** [comment]
Hi @Nihal987 Thanks for noticing the issue.

I have fixed it another Medium Story with [Group Replication using Docker Compose](https://medium.com/gitconnected/setting-up-mysql-group-replication-with-docker-compose-7639347545a2) but I forgot to update this story.

to fix it try to put `loose-` in all these vars:
```
  --loose-group-replication-start-on-boot='OFF' \
  --loose-group-replication-group-name='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' \
  --loose-group-replication-local-address="node$N:33061" \
  --loose-group-replication-group-seeds='node1:33061,node2:33061,node3:33061' \
  --loose-group-replication-single-primary-mode='OFF' \
  --loose-group-replication-enforce-update-everywhere-checks='ON'
```
Let me know. 

I was able to perform all the steps of the Medium story again, and the Medium story is updated.

**Comment by Nihal987** [comment]
Hi @wagnerjfr, thank you for getting back so quickly!

It's strange, I still have the same issues. Are you perhaps using an older version of the mysql docker image?
Just to be sure, here's my updated docker run command.

```
docker run -d --name=node1  \
-e MYSQL_ROOT_PASSWORD=mypass \
-v data:/var/lib/mysql \
mysql/mysql-server:8.0 \
--server-id=1 \
--log-bin='mysql-bin-1.log' \
--enforce-gtid-consistency='ON' \
--log-slave-updates='ON' \
--gtid-mode='ON' \
--transaction-write-set-extraction='XXHASH64' \
--binlog-checksum='NONE' \
--master-info-repository='TABLE' \
--relay-log-info-repository='TABLE' \
--plugin-load='group_replication.so' \
--relay-log-recovery='ON' \
--loose-group-replication-start-on-boot='OFF' \
--loose-group-replication-group-name='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' \
--loose-group-replication-local-address="node$N:33061" \
--loose-group-replication-group-seeds='node1:33061,node2:33061,node3:33061' \
--loose-group-replication-single-primary-mode='OFF' \
--loose-group-replication-enforce-update-everywhere-checks='ON'
```

**Comment by wagnerjfr** [comment]
Try to remove this `-v data:/var/lib/mysql`, I'm using Mac and I have had some issue with folder.
Before with Linux, I had no issues..

Btw, I just pulled the latest 8.0.. 
```
2023-08-09T16:20:06.588617Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
```

**Comment by wagnerjfr** [comment]
I can run your exactly same command without `-v data:/var/lib/mysql`:
```
docker run -d --name=node1  \
-e MYSQL_ROOT_PASSWORD=mypass \
mysql/mysql-server:8.0 \
--server-id=1 \
--log-bin='mysql-bin-1.log' \
--enforce-gtid-consistency='ON' \
--log-slave-updates='ON' \
--gtid-mode='ON' \
--transaction-write-set-extraction='XXHASH64' \
--binlog-checksum='NONE' \
--master-info-repository='TABLE' \
--relay-log-info-repository='TABLE' \
--plugin-load='group_replication.so' \
--relay-log-recovery='ON' \
--loose-group-replication-start-on-boot='OFF' \
--loose-group-replication-group-name='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee' \
--loose-group-replication-local-address="node$N:33061" \
--loose-group-replication-group-seeds='node1:33061,node2:33061,node3:33061' \
--loose-group-replication-single-primary-mode='OFF' \
--loose-group-replication-enforce-update-everywhere-checks='ON'
```
docker ps -a
```
CONTAINER ID   IMAGE                        COMMAND                  CREATED              STATUS                        PORTS                       NAMES
6a090a63edb4   mysql/mysql-server:8.0       "/entrypoint.sh --se…"   About a minute ago   Up About a minute (healthy)   3306/tcp, 33060-33061/tcp   node1
```

**Comment by Nihal987** [comment]
Yes that works!
Thank you so much!
I'm running Mac OS as well, I should've used Linux from the start

**Comment by wagnerjfr** [comment]
I wrote the 1st version of that tutorial in 2018, using Linux.. So, after 5 years, things changed and I forgot to confirm and update.
Thanks for trying and letting me know.

**Comment by Nihal987** [comment]
Thank you for the article! This is a very powerful and useful tool.
